### ISSUE TITLE
Issue with VoicePAT pretrained evaluation models `hyperparameters.yaml`

### ISSUE THREAD

**Issue by egaznep** [DigitalPhonetics/VoicePAT#2]
Inside e.g., `asv_pre_ecapa/hyperparameters.yaml`

Lines 52 and 53
```
    paths:
        embedding_model: !ref embedding_model.ckpt
```
cause the pretrained evaluation to not run (symlinks get created relative to the source code root and not according to the `models_dir.` Removing these (from all of the files) solve the issue.

**Comment by SarinaMeyer** [comment]
I uploaded new versions of the pretrained ASV models to [release v1](https://github.com/DigitalPhonetics/VoicePAT/releases/tag/v1)  with these lines removed.
I only found these lines in asv_pre_ecapa/hyperparameters.yaml and asv_pre_xvector/hyperparameters.yaml so I am not sure if I changed all the files that you meant. Please check and reopen if the issue persists.
