### ISSUE TITLE
Installation gets stuck

### ISSUE THREAD

**Issue by unilight** [DigitalPhonetics/VoicePAT#9]
Hi,

I am trying to run the installation without mamba. However, `make install pretrained_models` is stuck for hours.

```
$ make install pretrained_models
make: mamba: Command not found
Collecting package metadata (repodata.json): / WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0
WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.6.0.*, but conda is ignoring the .* and treating it as 1.6.0
WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .* and treating it as 1.7.1
done
Solving environment: \
```

I am wondering what takes so long...?

**Comment by egaznep** [comment]
Hi there!

Unfortunately, our packages come from a variety of repositories and to make the installation as widely supported as possible, we seldom put constraints - only when our code is really incompatible otherwise.

If your installation of `conda` is rather old (I think before 2023), the solver that came with `conda` back then is highly unoptimized and spends unnecessarily long to solve the packages. I would suggest either
- updating your solver https://conda.github.io/conda-libmamba-solver/user-guide/
-  or installing the latest version (that automatically comes with a good solver).
- or getting `mamba` by `conda install -c conda-forge mamba`

May I learn which `conda` version you use?

**Comment by unilight** [comment]
Hi @egaznep, thanks for the reply!
Turns out that my conda version was 4.1.0 -- much older than I thought... 

For anyone interested, I first tried to update my conda to the latest version (23.10). But solely doing this does not solve the stuck problem.
I then tried to install mamba by `conda install -c conda-forge mamba`, and then the installation somehow worked. It still took more than 30 minutes though.

@egaznep I then happened to find a bug in the Makefile -- this `cp` line does not have a destination.
https://github.com/DigitalPhonetics/VoicePAT/blob/main/Makefile#L40
What was the intention of this line?

**Comment by egaznep** [comment]
> Hi @egaznep, thanks for the reply! Turns out that my conda version was 4.1.0 -- much older than I thought...
> 
> For anyone interested, I first tried to update my conda to the latest version (23.10). But solely doing this does not solve the stuck problem. I then tried to install mamba by `conda install -c conda-forge mamba`, and then the installation somehow worked. It still took more than 30 minutes though.

Happy to hear that 🙂 the installation speed may be affected by your download speed and your computer specifications. I will run a test on my workstation to see if I get the same numbers and if it is possible to reduce the installation time.

> @egaznep I then happened to find a bug in the Makefile -- this `cp` line does not have a destination. https://github.com/DigitalPhonetics/VoicePAT/blob/main/Makefile#L40 What was the intention of this line?

I will issue a fix for that line soon, it should not be there. By the way, you might find the `vpc` branch useful, where a couple of extra developments have been made.

**Comment by unilight** [comment]
Thanks! Will take a look at the vpc branch and close this issue for now. I do have some other questions -- will ask in a separate issue.

**Comment by egaznep** [comment]
@unilight It seems that having an old, existing **Anaconda** is the primary reason why the installation drags on. I suggest using `miniconda` instead (which is not bloated with many packages therefore processes the installation specifications faster)
